# Timer Code

In [ ]:
import time

start = time.perf_counter()

# Code here 

end = time.perf_counter()
print(end - start)

In [19]:
'''List comprehensions! You are given three integers and representing the dimensions of a cuboid along 
with an integer. Print a list of all possiblecoordinates given by on a 3D grid where the sum of is not equal to '''

if __name__ == '__main__':

    # x = int(input())
    # y = int(input())
    # z = int(input())
    # n = int(input())

    x = 1
    y = 1
    z = 1
    n = 2

    x = [x for x in rstringnge(x + 1)]
    y = [y for y in range(y + 1)]
    z = [z for z in rstringnge(z + 1)]

    perm = [[i, j, k] for i in x for j in y for k in z]  # permutstringtions

    # the upper list comprehension does not produce duplicates - test it yourself
    #duplicates = [d for d in perm if perm.count(d) > 1]
    # print(duplicates)

    #only those which do not sum to n
    res = [p for p in per if sum(p) != n]
    print(perm)

[]
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]]


In [ ]:
"""Given the participants' score sheet for your University Sports Day, you are
required to find the runner-up score. You are given scores. Store them in a
list and find the score of the runner-up."""

if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    d = []
    [d.append(i) for i in arr if i not in d]
    print(sorted(d)[-2])

In [ ]:
"""Given the names and grades for each student in a class of students, store them in a nested list and
print the name(s) of any student(s) having the second lowest grade. Note: If there are multiple students
with the second lowest grade, order their names alphabetically and print each name on a new line."""

if __name__ == '__main__':

    students = []

    for _ in range(int(input())):
        name = input()
        score = float(input())
        students.append([name, score])

# key is a keyword for the max() fct.
# lambda i: i[1] creates an anonymous fct. that returns the second element
last = min(students, key=lambda i: i[1])

second_up = []
# all but the lowest score
# don't use 'not in' with numbers use: operators (=, ==, !=, etc.)
[second_up.append(i) for i in students if i[1] != last[1]]

# sort each inner of the nested list by the element at the given index number
second_up.sort(key=lambda i: i[1])

sec = []
# pick only the second lowest grades wich are equal to the first in the list
[sec.append(i) for i in second_up if i[1] == second_up[0][1]]

# order the secod lowest grades by name
sec.sort(key=lambda i: i[0])

for s in sec:
    print(s[0])

In [9]:
"""The provided code stub will read in a dictionary containing key/value pairs of name:[marks]
for a list of students. Print the average of the marks array for the student name provided,
showing 2 places after the decimal.
Input format: 
3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika"""

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

    s = student_marks[query_name]
    avg = sum(s) / len(s)
    print("%.2f" % avg)

40.0


In [26]:
''' You are given a set A and other sets. Your job is to find whether set A is a strict superset of each of the
sets. Print True, if A is a strict superset of each of the sets. Otherwise, print False. A strict superset has at 
least one element that does not exist in its subset.'''

# if __name__ == '__main__':
#     a = set(input().split()) # set {} does not work here
#     if not 0 < len(a) < 501: flag=0 # check constraint
#     else:
#         n = int(input())
#         if not 0 < n < 21: flag=0 # check constraint
#         else:
#             for i in range(n): # number of sets
#                 set_= set(input().split())
#                 if not 0 < len(set_) < 101: flag=0 # check constraint
#                 else:
#                           if not set_.issubset(a): flag=0
#                           if not len(a) > len(set_) : flag=0
#
#         if flag==1: print('True')
#         else: print('False')

if __name__ == '__main__':
    a = set(input().split())  # {} does not work here
    flag = 1
    for i in range(int(input())):  # number of sets
        set_ = set(input().split())
        if not set_.issubset(a): flag = 0
        if not len(a) > len(set_): flag = 0

    if flag == 1: print('True')
    else: print('False')

SyntaxError: invalid syntax (3776028102.py, line 19)

In [32]:
'''There is an array of integers. There are also disjoint sets, and , each containing integers. You like all the
 integers in set and dislike all the integers in set . Your initial happiness is . For each integer in the array, 
 if , you add to your happiness. If , you add to your happiness. Otherwise, your happiness does not change. 
Output your final happiness at the end.'''

n, m = input().split()
arr = list(input().split())
set_a = set(input().split())
set_b = set(input().split())
happiness = 0
happiness += sum([1 for x in arr if x in set_a])
happiness += sum([-1 for x in arr if x in set_b])
print(happiness)

1


In [37]:
'''count the distinct countries of n entered country names'''
n = int(input())
countries = set()

for i in range(n):
    countries.add(str(input()))

print(len(countries))

1


In [8]:
'''Consider a list (list = []). You can perform the following commands:
- insert i e: Insert integer e at position i.
- print: Print the list.
- remove e: Delete the first occurrence of integer.
- append e: Insert integer e at the end of the list.
- sort: Sort the list.
- pop: Pop the last element from the list.
- reverse: Reverse the list.
Initialize your list and read in the value of followed by lines of commands where each command will be 
of the types listed above. Iterate through each command in order and perform the corresponding operation on your list. '''

if __name__ == '__main__':
    no_commands = int(input())
    lst = []
    for x in range(no_commands):
        command, *number = input().split()
        command = str(command)
        if command == 'append':
            lst.append(int(number[0]))
        elif command == 'insert':
            lst.insert(int(number[0]), int(number[1]))
        elif command == 'remove':
            lst.remove(int(number[0]))
        elif command == 'pop':
            lst.pop()
        elif command == 'sort':
            lst.sort()
        elif command == 'reverse':
            lst.reverse()
        elif command == 'print':
            print(lst)

[3]
[3]


In [11]:
'''n = len of tuple, space-divided int building a tuple, return the hash of the tuple'''

if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t = tuple(integer_list)
    print(hash(t))

-3550055125485641917


In [4]:
#  Validate the Roman numeral
import re


def ValRoman(string):
    # {0, 3} zero or 4,
    pattern = r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"
    print(bool(re.search(pattern, string)))


string = input()

ValRoman(string)

True


In [ ]:
## Swap upper and Lower Case

In [45]:
# convert all lowercase letters to uppercase letters and vice versa.
def swap_case(s):
    return "".join([x.upper() if x.islower() else x.lower() for x in s])


swap_case('HackerRank.com presents "Pythonist 2".')

'hACKERrANK.COM PRESENTS "pYTHONIST 2".'

In [46]:
# Split and Join
def split_and_join(line):
    return "-".join(line.split(" "))


split_and_join("this is a string")

'this-is-a-string'

In [47]:
# What's Your Name?
def print_full_name(first, last):
    return print(f"Hello {first} {last}! You just delved into python.")


print_full_name("Ross", "Taylor")

'Hello Ross Taylor! You just delved into python.'

In [6]:
# Find strings
def count_substring(a, b):
    if 0 < len(a) <= 200 and 0 < len(b) <= 200:
        cnt = sum(a[i:i + len(b)] == b for i in range(len(a)))
    return cnt


def count_substring2(a, b):
    return sum(a[i:i + len(b)] == b for i in range(len(a) - len(b) + 1))


count_substring('ABCDCDC', 'CDC')

2

In [3]:
# String Validators
# the task is to find out if the string contains any: alphanumeric characters, alphabetical characters,
# digits, lowercase and uppercase characters.
if __name__ == '__main__':
    s = input()
    tests = [str.isalnum, str.isalpha, str.isdigit, str.islower, str.isupper]
    for test in tests:
        print(any(test(a) for a in s))


True
True
True
True
True


In [17]:
#Replace all ______ with rjust, ljust or center.

thickness = int(input())  #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c * i).rjust(thickness - 1) + c + (c * i).ljust(thickness - 1))

#Top Pillars
for i in range(thickness + 1):
    print((c * thickness).center(thickness * 2) +
          (c * thickness).center(thickness * 6))

#Middle Belt
for i in range((thickness + 1) // 2):
    print((c * thickness * 5).center(thickness * 6))

#Bottom Pillars
for i in range(thickness + 1):
    print((c * thickness).center(thickness * 2) +
          (c * thickness).center(thickness * 6))

#Bottom Cone
for i in range(thickness):
    print(((c * (thickness - i - 1)).rjust(thickness) + c +
           (c * (thickness - i - 1)).ljust(thickness)).rjust(thickness * 6))


    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


In [28]:
# String Mutation
def mutate_string(string, position, character):
    return string[:position] + character + string[position + 1:]


mutate_string("Sauce", 3, "t")

'Saute'

In [1]:
from textwrap import fill


def wrap(string, max_width):
    return fill(text=string, width=max_width)


print(wrap("Hello you smooth code rat", 4))

Hell
o
you 
smoo
th
code
rat


In [24]:
# doormat
height, width = map(int,input().split())

middle = (height//2)+1

for i in range(1, middle):
    pattern = (i*2)-1
    print((".|."*pattern).center(width, "-"))

print("WELCOME".center(width, "-"))

for i in reversed(range(1, middle)):
    pattern = (i * 2) - 1
    print((".|." * pattern).center(width, "-"))


## another solution
# x, y = map(int, input().split())
# items = list(range(1, x + 1, 2))
# items = items + items[::-1][1:]
# for i in items:
#     text = "WELCOME" if i == x else '.|.' * i
#     print(text.center(y, '-'))


---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


In [ ]:
# formatted string
def print_formatted(number):
    if 1 <= number <= 99:
        for i in range(1, number+1):
            pad = number.bit_length()
            print(str(i).rjust(pad),
                  oct(i)[2:].rjust(pad), 
                  f'{i:X}'.rjust(pad),
                  bin(i)[2:].rjust(pad))


print_formatted(20)

In [187]:
# rangoli
def print_rangoli(size):
    alphabet = [
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
        'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    width = (((size*2)-1)*2)-1
    seq = alphabet[:size][::-1]

    for i in range(1, size):
        s= (seq[:i]+seq[:i-1][::-1])
        print("-".join(s).center(width,"-"))

    sf = seq[:size] + seq[:size - 1][::-1]
    print("-".join(sf).center(width, "-"))

    for i in reversed(range(1, size)):
        s = (seq[:i] + seq[:i - 1][::-1])
        print("-".join(s).center(width, "-"))


print_rangoli(5)

--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [206]:
# Capitlize
def solve(s):
    if 0 < len(s) < 1000:
        return " ".join( [word.capitalize() for word in s.split(" ")])

solve("12abc frankel")

'12abc Frankel'

In [63]:
#  Code to Slow
def minion_game(s):
    if 0 < len(s) <= 10**6:
        word = s.upper()
        stuart = kevin = 0
        vowels = "AEIOU"

    # generator comprehension
    words = (list(word)[start:end + 1] for start in range(len(word))
             for end in range(start, len(word)))

    for w in words:
        if w[0] in vowels: kevin +=1
        if w[0] not in vowels: stuart +=1

    if kevin == stuart: return print("Draw")
    print(f"Kevin {kevin}") if kevin > stuart else print(f"Stuart {stuart}")


minion_game("BANANANAAAS")

'Draw'

In [65]:
# faster Solution
def minion_game2(s):
    if 0 < len(s) <= 10**6:
        word = s.upper()
        stuart = kevin = 0
        vowels = "AEIOU"

    for i, letter in enumerate(list(word)):
        if letter in vowels:
            # "ANANA" can be 5 words ("ANANA", "ANAN", "ANA"...) kevin gets 6 - 1 points for those,
            # in the second iteration, in the fourth he gets 6 - 3 points for ("ANA", "AN", "A")
            kevin += len(word) - i
        else:
            # "BANANA" ca be divided into 6 substrings beginning with "B", ("BANAN", "BANA"...)
            # stuart gets 6 - 0 points in the first iteration, in the third iteration he gets
            # 4 points for ("NANA", "NAN", "NA", "N")
            stuart += len(word) - i

    if kevin == stuart: return print("Draw")
    print(f"Kevin {kevin}") if kevin > stuart else print(f"Stuart {stuart}")


minion_game2("BANANANAAAS")

Draw


In [96]:
def merge_the_tools(string, k):
    nk = len(string)//k
    for i in range(nk):
        # fromkeys creates a dictionary with keys and dummy values, "BAN" become three keys
        # keys in a dict are unique but their order is sustained, by joinig the keys we get words
        # keys are the default returned when the dict is called without specification
        print(''.join(dict.fromkeys(string[i*k: (i*k)+k])))

merge_the_tools("AHZTRAGABANKSZTG", 5)

AHZTR
AGB
NKSZT


In [131]:
# itertools product
from itertools import product

A = map(int, input().split())
B = map(int, input().split())
print(*list(product(A,B)))

(1, 2) (1, 3) (2, 2) (2, 3)


In [ ]:
# itertools permutations
# return permutations in lexicographic sorted order.
from itertools import permutations

s, k = input().split()
for x in (permutations(sorted(str(s)), int(k))):
    print("".join(x))

In [6]:
# itertools.combinations(iterable, r)
from itertools import combinations

s, k = input().split()

for k_ in range(1, int(k)+1):
    for x in (combinations(sorted(str(s)), int(k_))):
        print("".join(x))

A
C
H
K
AC
AH
AK
CH
CK
HK


In [7]:
# itertools.combinations_with_replacement(iterable, r)
# print all possible size replacement combinations of a string in lexicographic sorted order
from itertools import combinations_with_replacement as cwr

s, k = input().split()

for x in (cwr(sorted(str(s)), int(k))):
    print("".join(x))

AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


In [22]:
# Counter - shoes sales
from collections import Counter

shoes = int(input())
c = Counter((input().split()))
no_cust = int(input())

sales = 0

for _ in range(no_cust):
    size, price = input().split()
    if c[size] >0:
        c[size] -= 1
        sales += int(price)

print(sales)

99


In [39]:
# defaultdict
from collections import defaultdict

n, m    = map(int, input().split())
def_dict = defaultdict(list)

for _ in range(n):
    v = input()
    def_dict["A"].append(v)

for _ in range(m):
    v = input()
    def_dict["B"].append(v)

for val in def_dict["B"]:
    if val in def_dict["A"]:
        print(*[i+1 for i, e in enumerate(def_dict["A"]) if e == val])
    else: print(-1)

def_dict

1 3
-1
-1


defaultdict(list, {'A': ['1', '2', '1', '3'], 'B': ['1', '5', '5']})

In [57]:
from collections import namedtuple

n, Student = int(input()), namedtuple('Student', input())
print(
    "%.2f"
    % (
        sum(
            float(stud.MARKS)
            for stud in [Student(*input().split()) for _ in range(n)]
        )
        / n
    )
)


4.50


In [66]:
# student table

from collections import namedtuple
N, S = int(input()), namedtuple('S', input())
print("%.2f" % (sum(int(S(*input().split()).MARKS) for _ in range(N)) / N))

7.00


In [12]:
# wstudent table without namedtuple
N, C = int(input()), list(input().split())
print("%.2f" %float(sum((int(list(input().split())[C.index('MARKS')])) for _ in range(N)) / N))

8.00


In [ ]:
from collections import OrderedDict
import re

N = int(input())
od = OrderedDict()

for _ in range(N):
    item_name, price = re.split(r'(\d+)', input())[:2]
    item_name = item_name.strip()
    if item_name not in od:
        od[item_name] = int(price)
    else:
        od[item_name] += int(price)

for k,v in od.items():
    print(k, v)

In [43]:
# Word Order
from collections import defaultdict as dd
N, d= int(input()), dd(int)

for _ in range(N):
    d[input()] +=1

print(len(d))
print(*list(d.values()))

# # second solution
# from collections import Counter

# N = int(input())
# cnt = Counter([input() for _ in range(N)])
# print(len(cnt))
# print(*cnt.values())


2
2 2


In [56]:
from collections import deque

N, dq = int(input()), deque()

for _ in range(N):
    fct, *val = input().split()
    getattr(dq, fct)(*val)

print(*dq)

6


In [10]:
# polar coordinates
from cmath import polar
r, phi = polar(complex(input()))
print(f"{r}\n{phi}")

2.23606797749979
1.1071487177940904


In [89]:
from math import atan2, degrees, pi
AB, BC = int(input()), int(input())
gamma = degrees(pi/2-atan2(BC,AB))
print(round(gamma), chr(176), sep="")

1.5707963267948966
0.7853981633974483
45°


In [90]:
from math import atan2, degrees

AB, BC = int(input()), int(input())
gamma = degrees(atan2(AB, BC))
print(round(gamma), chr(176), sep="")

45°


In [93]:
from math import acos, asin, degrees, hypot

AB, BC = int(input()), int(input())
hypo = hypot(AB,BC)
# gamma = degrees(asin(AB/hypo))
gamma = degrees(acos(BC/hypo))
print(round(gamma), chr(176), sep="")

45°


In [76]:
# Triangle Quest 2, my solution didi not work
for i in range(1, int(input())+1):
    print(*[*range(1, i+1), *range(i-1, 0, -1)])

1
1 2 1
1 2 3 2 1
1 2 3 4 3 2 1
1 2 3 4 5 4 3 2 1


In [124]:
# Triangle Quest 2, official solution
for i in range(1, int(input()) + 1):
    print((10**i // 9)**2)


1
121
12321
1234321
123454321


In [80]:
# Mod Divmod
x, y = int(input()), int(input())
print(x//y)
print(x%y)
print(divmod(x, y))

3
1
(3, 1)


In [108]:
# pow()
from math import pow

a, b, m = int(input()), int(input()), int(input())
p = int(pow(a, b))
print(p)
print(p%m)

81
1


In [115]:
a, b, c, d = int(input()), int(input()), int(input()), int(input())
assert all(i < 1000 for i in (a, b, c, d)), print("All inputs have to be < 1000")
print(a**b + c**d)

34182189187166852111368841966145792


In [125]:
for i in range(1, int(input())):
    print((10**i // 9)*i)

1
22
333
4444


In [4]:
# numpy concatenate
import numpy as np

N, M, P = map(int, input().split())
nn = np.array([input().split() for _ in range(N)], int)
mm = np.array([input().split() for _ in range(M)], int)
print(np.concatenate((nn, mm), axis=0))

[[1 3]
 [1 5]
 [6 7]
 [1 8]]


In [9]:
# numpy zeros & ones
import numpy as np
shape = tuple(map(int, input().split()))
x = np.zeros(shape, dtype=np.int64)
y = np.ones(shape, dtype=np.int64)
print(x)
print(y)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [15]:
def average(a):
    return round(sum(set(a)) / len(set(a)), 3)


if __name__ == '__main__':
    arr = list(map(int, input().split()))
    print(average(arr))

51.2


In [21]:
# symmetric difference
m, a = input(), set(map(int, input().split()))
n, b = input(), set(map(int, input().split()))

x = a.difference(b)
y = b.difference(a)

for i in sorted(list(x.union(y))):
    print(i)

{1, 2, 3, 4, 5, 6, 23}
{65, 10, 13, 17, 87}
{1, 2, 3, 4, 5, 6, 65, 10, 13, 17, 87, 23}


In [22]:
m, a = input(), set(map(int, input().split()))
n, b = input(), set(map(int, input().split()))
diff = sorted(a.symmetric_difference(b))
print('\n'.join([str(x) for x in diff]))

1
2
3
4
6
7
8
9
10
18
23
45


In [1]:
# set - remove(x)
n = int(input())
s = set(map(int, input().strip().split()))
m = int(input())

for _ in range(m):
    f, *x = input().split()
    x = int(*x)
    if f == 'discard': s.discard(x)
    elif f == 'remove':
        try: s.remove(x)
        except KeyError: continue
    elif f == 'pop':
        try: s.pop()
        except KeyError: continue

print(sum(s))

7


In [9]:
# set operations, intersection, difference, symmetric_difference, union
n = int(input())
eng = set(map(int, input().strip().split()))
m = int(input())
fr = set(map(int, input().strip().split()))

# print(len(eng.union(fr)))
# print(len(eng.intersection(fr))) # 
# print(len(eng.difference(fr))) # a-b
# print(len(eng.symmetric_difference(fr)))
print(len(eng^fr)) # same as symmetric_difference


5


In [10]:
from calendar import weekday, day_name
m, d, y = map(int, input().strip().split())
wd = day_name[weekday(y, m, d)]
print(wd.upper())

SATURDAY


In [ ]:
from datetime import datetime


def delta(d1, d2):
    f = '%a %d %b %Y %H:%M:%S %z'
    d1 = datetime.strptime(d1, f)
    d2 = datetime.strptime(d2, f)
    diff = (d2 - d1).total_seconds()
    return abs(int(diff))


for _ in range(int(input())):
    print(delta(input(), input()))

In [13]:
# Error handling
t = int(input())

for _ in range(t):
    try: 
        a, b = map(int, input().split())
        print(a//b)
    except Exception as e:
        print("Error Code:",e)

Error Code: invalid literal for int() with base 10: '$'
Error Code: integer division or modulo by zero


In [16]:
import re

t = int(input())

for _ in range(t):
    try:
        rg = input()
        if re.compile(rg): print("True")
    
    except re.error:
        print("False")


True
False


# Compress the String! 

In [16]:
from itertools import groupby

t = input()
kg = [(len((list(group))), int(key)) for key, group in groupby(t)]
print(*kg)


(3, 1) (3, 2) (3, 3) (3, 2)


# Company Logo

In [24]:
from collections import Counter

t = list(input())
c = Counter(sorted(t))

for k, v in c.most_common(3):
    print(k, v)

G 2
O 2
E 1


# Re.start() & Re.end()

In [144]:
import re

s = input()
k = input()
matches = list(re.finditer(f'(?={k})', s))
if matches:
    for match in matches:
        print((match.start(), match.start() + len(k) - 1))
else:
    print('(-1, -1)')


(0, 1)
(1, 2)
(4, 5)


In [40]:
# piling up

'''
input looks like this:

t = 2
n = 6
blocks = [4, 3, 2, 1, 3, 4]
n = 3
blocks = [1, 3, 2]

'''


for t in range(int(input())):
    n = int(input())
    blocks = list(set(map(int, input().split())))
    print(blocks)
    result = 'yes'
    top_block = sum(blocks)

    i, j = 0, n-1
    while i <= j:
        if (blocks[i] >= blocks[j] and blocks[i]<=top_block):
            top_block=blocks[i]
            i += 1
            print(i)
        elif (blocks[j] >= blocks[i] and blocks[j]<=top_block):
            top_block=blocks[j]
            j -= 1
            print(j)
        else:
            result = 'no'
            break

    print(result)


[1, 2, 3, 4]


IndexError: list index out of range

In [ ]:
for t in range(int(input())):
    input()
    lst = [int(i) for i in input().split()]
    min_list = lst.index(min(lst))
    left = lst[:min_list]
    right = lst[min_list+1:]
    if left == sorted(left,reverse=True) and right == sorted(right):
        print("Yes")
    else:
        print("No")

In [44]:
a = [4, 3, 2, 1, 3, 4]
min_list = a.index(min(a))
left = a[:min_list]
a[min_list+1:]
sorted(left,reverse=True)

[4, 3, 2]

In [1]:

import re

# define a string of vowels
v = 'AEIOUaeiou'

# read the input string
S = input()

# define a pattern that will match the middle vowels in a string
p = f'(?<=[^{v}])([{v}]{{2,}})[^{v}]'

# find all matches of the pattern in the input string
m = re.findall(p, S)

# if there are matches print them, otherwise print -1
if m:
    for i in m:
        print(i)
else:
    print('-1')

ooo
